# Generated by Django 3.2.13 on 2022-10-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_movie_running_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='running_time',
        ),
    ]
