# Generated by Django 3.2.13 on 2022-10-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_movie_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.movie'),
            preserve_default=False,
        ),
    ]
