# Generated by Django 3.2.13 on 2022-10-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.TextField(),
        ),
    ]
