# Generated by Django 3.2.13 on 2022-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
