-- 1.
SELECT ANIMAL_TYPE, COUNT(*) FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog'
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- 2.
SELECT NAME, COUNT(*) FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*) >= 2
ORDER BY NAME;

-- 3.
SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*)
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= 9
  AND DATE_FORMAT(DATETIME, '%H') < 20
GROUP BY HOUR
ORDER BY HOUR;

-- 4. ?????????????????????
WITH RECURSIVE HOURS AS (
  SELECT 0 AS H
  UNION ALL
  SELECT H + 1 FROM HOURS
  WHERE H < 23
)

SELECT H, COUNT(HOUR(ANIMAL_OUTS.DATETIME)) FROM HOURS
LEFT JOIN ANIMAL_OUTS
    ON HOURS.H = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOURS.H
ORDER BY HOURS.H;